DROP DATABASE BookStore;
DROP DATABASE Bank;
DROP DATABASE DeliveryCo;
DROP DATABASE EmailService;

CREATE DATABASE BookStore;
CREATE DATABASE Bank;
CREATE DATABASE DeliveryCo;
CREATE DATABASE EmailService;